version: '3.4'

services:
  iptintegrityinspector:
    image: gbifnorway/ipt-integrity-inspector:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
